### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wongsyrone** [wongsyrone/shadowsocks-android#1]
- [ ] update ndk and build tools
- [ ] explore mbedtls on android
- [ ] merge important changes from upstream

**Comment by wongsyrone** [comment]
ndk-stack output
```
********** Crash dump: **********
Build fingerprint: 'google/angler/angler:6.0.1/MTC19T/2741993:user/release-keys'
pid: 14425, tid: 14425, name: ss-tunnel  >>> /data/user/0/com.github.shadowsocks/ss-tunnel <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x5585dba2d0
Stack frame #00 pc 000000000005dcb0  /data/data/com.github.shadowsocks/ss-tunnel: Routine cork_error_set_printf at /home/wong/shadowsocks-android/src/main/jni/shadowsocks-libev/libcork/core/error.c:143
Stack frame #01 pc 000000000005de38  /data/data/com.github.shadowsocks/ss-tunnel: Routine cork_buffer_append_vprintf at /home/wong/shadowsocks-android/src/main/jni/shadowsocks-libev/libcork/ds/buffer.c:188
Stack frame #02 pc 000000000005dc34  /data/data/com.github.shadowsocks/ss-tunnel: Routine cork_error_set_printf at /home/wong/shadowsocks-android/src/main/jni/shadowsocks-libev/libcork/core/error.c:135
Stack frame #03 pc 000000000001eb68  /data/data/com.github.shadowsocks/ss-tunnel: Routine read_jconf at /home/wong/shadowsocks-android/src/main/jni/shadowsocks-libev/src/jconf.c:144
Stack frame #04 pc 0000000000016df4  /data/data/com.github.shadowsocks/ss-tunnel: Routine main at /home/wong/shadowsocks-android/src/main/jni/shadowsocks-libev/src/tunnel.c:950
Stack frame #05 pc 000000000001bc98  /system/lib64/libc.so (__libc_init+100)
Stack frame #06 pc 00000000000168cc  /data/data/com.github.shadowsocks/ss-tunnel: Routine main at /home/wong/shadowsocks-android/src/main/jni/shadowsocks-libev/src/tunnel.c:712
```

**Comment by wongsyrone** [comment]
aarch64

ac_cv_c_littleendian=${ac_cv_c_littleendian=yes}
ac_cv_sizeof_long_int=8
ac_cv_sizeof_long=8
ac_cv_sizeof_size_t=8
ac_cv_sizeof_ssize_t=8
ac_cv_sizeof_unsigned_long=8
ac_cv_sizeof_void_p=8

arm

ac_cv_c_littleendian=${ac_cv_c_littleendian=yes}
ac_cv_sizeof_long_int=4
ac_cv_sizeof_long=4
ac_cv_sizeof_size_t=4
ac_cv_sizeof_ssize_t=4
ac_cv_sizeof_unsigned_long=4
ac_cv_sizeof_void_p=4

**Comment by dcreager** [comment]
Your debug stack trace points to [this line](https://github.com/redjack/libcork/blob/develop/src/libcork/core/error.c#L85), which is where we get a thread-local variable that we can store an error message into.  Our TLS implementation is [here](https://github.com/redjack/libcork/blob/develop/include/libcork/threads/basics.h#L140); somehow that's returning a NULL pointer.  I don't have the time debug more deeply than this, unfortunately, but hopefully those links will help you track down the cause.

**Comment by dcreager** [comment]
Also, there are a couple of different TLS implementations; our [autodetection logic](https://github.com/redjack/libcork/blob/develop/include/libcork/config/gcc.h#L77) is probably picking the `__thread` storage specifier if you're using GCC (or something that claims GCC compatibility via the preprocessor macros), and falling back on the pthreads implementation [otherwise](https://github.com/redjack/libcork/blob/develop/include/libcork/config/linux.h#L31).

**Comment by wongsyrone** [comment]
I'm using clang since NDK starts deprecating gcc. Can this related to internal predefined macros?

**Comment by dcreager** [comment]
I *think* clang might define the GCC macros to claim compatibility with GCC, but I'm not certain on that.  You're definitely getting one of the two TLS implementations; if not, you'd get a [fatal error message](https://github.com/redjack/libcork/blob/develop/include/libcork/threads/basics.h#L217) when you try to compile.  If you want to skip the autodetection logic completely, you can follow the instructions [here](http://libcork.readthedocs.io/en/0.14.0/config/#skipping-autodetection).  Then you'll just have to set all of the configuration macros by hand in some part of your build scripts.

**Comment by wongsyrone** [comment]
Also I found [this](https://android-review.googlesource.com/#/c/207721/5/build/core/toolchains/aarch64-linux-android-clang3.6/setup.mk) indicating they are using `-fstrict-aliasing`, can this mess up new code?

**Comment by dcreager** [comment]
That should be okay; `-fstrict-aliasing` is turned on with `-O3`, which is what the libcork [CI tests](https://github.com/redjack/libcork/blob/develop/.travis/test#L24) use.

**Comment by wongsyrone** [comment]
Found

> Fixed __thread so that it works for real this time.

in NDK r12 [release note](https://developer.android.com/ndk/downloads/index.html), this might be a toolchain issue, will give it a try

**Comment by wongsyrone** [comment]
@dcreager 
confirmed NDK r12 works well, thanks for your help, the root cause is `__thread` not working on NDK r11c.
